In [1]:
import  tensorflow_io as tfio
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
def mono_16k(path):
    file_contents = tf.io.read_file(path)
    wav ,sample_rate = tf.audio.decode_wav(file_contents, desired_channels = 1)
    wav = tf.squeeze(wav, axis = -1)
    sample_rate = tf.cast(sample_rate, dtype= tf.int64)
    #wav = tfio.audio.resample(wav, rate_in = sample_rate, rate_out = 16000)
    return wav

In [24]:
#path="C:/Users/shubh/OneDrive/Desktop/eveythingeverywhereallatonce/Btech/MINI PROJECT/Voice Automation/Dataset/one/0a2b400e_nohash_3.wav"
path = "C:/Users/shubh/OneDrive/Desktop/eveythingeverywhereallatonce/Btech/MINI PROJECT/Voice Automation/Code/output4.wav"

In [25]:
k=mono_16k(path)

In [26]:
print(k)

tf.Tensor(
[ 0.0000000e+00  0.0000000e+00 -3.0517578e-05 ...  1.2573242e-02
  8.2092285e-03  5.9204102e-03], shape=(15360,), dtype=float32)


In [27]:
tf.shape(k)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([15360])>

In [28]:
"""def make_spectrogram(wav):
    spectrogram = tf.signal.stft(wav, frame_length= 320, frame_step=32)
    spectrogram = tf.abs(spectrogram)
    spectrogram = tf.expand_dims(spectrogram, axis =2)
    return spectrogram"""

'def make_spectrogram(wav):\n    spectrogram = tf.signal.stft(wav, frame_length= 320, frame_step=32)\n    spectrogram = tf.abs(spectrogram)\n    spectrogram = tf.expand_dims(spectrogram, axis =2)\n    return spectrogram'

In [29]:
def make_spectrogram(wav):
  input_len = 16000
  wav = wav[:input_len]
  zero_padding = tf.zeros([16000] - tf.shape(wav),dtype=tf.float32)
  wav = tf.cast(wav, dtype=tf.float32)
  equal_length = tf.concat([wav, zero_padding], 0)
  spectrogram = tf.signal.stft(equal_length, frame_length=320, frame_step=32)
  spectrogram = tf.abs(spectrogram)
  spectrogram = tf.expand_dims(spectrogram, axis =2)


  return spectrogram

In [30]:
spectogram=make_spectrogram(k)

In [31]:
tf.shape(spectogram)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([491, 257,   1])>

In [32]:

spectogram=tf.reshape(spectogram, (491, 1, 257))
tf.shape(spectogram)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([491,   1, 257])>

In [33]:
model=tf.keras.models.load_model("C:/Users/shubh/OneDrive/Desktop/eveythingeverywhereallatonce/Btech/MINI PROJECT/Voice Automation/Code/VOICE_NEW")

In [34]:
config = model.get_config() # Returns pretty much every information about your model
print(config["layers"][0]["config"]["batch_input_shape"])
print(tf.shape(spectogram))

(None, 491, 1, 257)
tf.Tensor([491   1 257], shape=(3,), dtype=int32)


In [35]:
spectogram = spectogram[tf.newaxis,...]

In [36]:
tf.shape(spectogram)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  1, 491,   1, 257])>

In [37]:
prediction=model.predict(spectogram)

1/1 [==============================] - 0s 321ms/step


In [38]:
o=max(prediction[0])
print(o)
prediction[0]

9.73829


array([ 4.3629756 ,  6.0300393 ,  1.0555897 , -4.0034103 ,  9.73829   ,
       -3.148623  , -6.4670453 , -1.1006742 , -4.0417013 , -0.88610214,
       -1.2877094 ,  0.07541627,  0.24884878], dtype=float32)

In [39]:
ind_np = ((np.where(prediction[0] ==o ))[0])

In [40]:
index = (ind_np[0])

In [41]:
print(index)

4


In [42]:
list_label=['down', 'go', 'left', 'marvin', 'no' ,'off' ,'on', 'one' ,'right', 'stop', 'up', 'yes' ,'zero']

In [43]:
len(list_label)

13

In [44]:
print(list_label[index])

no
